/* config.h.  Generated by configure.  */

/* Define to enable diagnostic debugging support. */
/* #undef DEBUG */

/* Define to enable experimental code. */
/* #undef EXPERIMENTAL */

/* Define to disable debugging assertions. */
#define NDEBUG

/* Define to optimize for accuracy over speed. */
/* #undef OPT_ACCURACY */

/* Define to optimize for speed over accuracy. */
#define OPT_SPEED 1

/* Define to enable a fast subband synthesis approximation optimization. */
#define OPT_SSO

/* Define to influence a strict interpretation of the ISO/IEC standards, even
   if this is in opposition with best accepted practices. */
/* #undef OPT_STRICT */

#define FPM_DEFAULT
